---
# set these parameters to control the region, keypair, and AMI that are launched
ec2_region: us-east-2
instances_keypair: deepak2717 
image_id: ami-03291866

# security groups to be created
security_groups:
  - name: ssh
    desc: the security group for the jumphost
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

# Optional security group
  - name: web
    desc: the security group for the web server 
    rules:
      - proto: tcp
        from_port: "80"
        to_port: "80"
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "443"
        to_port: "443"
        cidr_ip: 0.0.0.0/0
  
ec2_instances:
  - instance_type: t2.micro
    image: "{{ image_id }}"
    assign_public_ip: true
    keypair: "{{instances_keypair}}"
    group: ['ssh']
    instance_tags: 
        Name: dev_jumphost
    exact_count: 1
    count_tag: 
        Name: dev_jumphost
